version: '3'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb://admin:password@mongodb:27017/?retryWrites=true&w=majority
      - MONGO_DATABASE=Cluster0
      - MONGO_POOLSIZE=5
      - LOG_DIR=/log
      - APP_PORT=3001

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongodb_data:
